//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string PlayerID { get; set; }
        public string PlayerName { get; set; }
        public Nullable<decimal> MinsPerGame { get; set; }
        public Nullable<decimal> EffPerGame { get; set; }
        public Nullable<decimal> EffMin { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public Nullable<decimal> FieldsGoalPercentage { get; set; }
        public Nullable<decimal> ThreePointsPercentage { get; set; }
        public Nullable<decimal> FreeThrowsPercentage { get; set; }
        public Nullable<decimal> ReboundsPerGame { get; set; }
        public Nullable<decimal> AssistsPerGame { get; set; }
        public Nullable<decimal> StealsPerGame { get; set; }
        public Nullable<decimal> BlocksPerGame { get; set; }
        public Nullable<decimal> TurnoversPerGame { get; set; }
        public Nullable<decimal> PointsPerGame { get; set; }
    }
}
